substitutions:   # Main-Seeed-Xiao-ESP32-C3.yaml
  device_name: xiao-1
  friendly_name: XIAO32 1 (180)
  api_key: "fmlpfRzTy+RXkwsNjjdKiGJDPWFKRWsqwDxk4fyAEBI="  # Commented out: Disables API encryption for testing per your request.
  ota_password: "dba6cbb118b753240121b7d266f9ff56"  # Keep uncommented: Secure OTA password as previously agreed.
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  run_min_initial: '240'  # Initial run min (seconds)
  sleep_dur_initial: '120'  # Initial sleep duration (seconds)
  countdown_dur: '30'  # Countdown length (seconds)

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

  on_boot:
    priority: -100
    then:
      - lambda: |-
          ESP_LOGI("boot", "[BOOT] Device booting...");
          const char *reason_str;
          esp_reset_reason_t reason = esp_reset_reason();
          switch (reason) {
            case ESP_RST_UNKNOWN:     reason_str = "Unknown"; break;
            case ESP_RST_POWERON:     reason_str = "Power On"; break;
            case ESP_RST_EXT:         reason_str = "External Reset"; break;
            case ESP_RST_SW:          reason_str = "Software Reset"; break;
            case ESP_RST_PANIC:       reason_str = "Panic"; break;
            case ESP_RST_INT_WDT:     reason_str = "Interrupt WDT"; break;
            case ESP_RST_TASK_WDT:    reason_str = "Task WDT"; break;
            case ESP_RST_WDT:         reason_str = "Other WDT"; break;
            case ESP_RST_DEEPSLEEP:   reason_str = "Deep Sleep Wake"; break;
            case ESP_RST_BROWNOUT:    reason_str = "Brownout"; break;
            case ESP_RST_SDIO:        reason_str = "SDIO"; break;
            case ESP_RST_USB:         reason_str = "USB"; break;
            case ESP_RST_JTAG:        reason_str = "JTAG"; break;
            case ESP_RST_EFUSE:       reason_str = "Efuse"; break;
            case ESP_RST_PWR_GLITCH:  reason_str = "Power Glitch"; break;
            case ESP_RST_CPU_LOCKUP:  reason_str = "CPU Lockup"; break;
            default:                  reason_str = "Unknown"; break;
          }
          ESP_LOGI("reset", "[BOOT] Reset reason: %d (%s)", reason, reason_str);
          id(esp_reset_reason_text).publish_state(reason_str);
          ESP_LOGI("boot", "[BOOT] Initial uptime: %.1fs", id(esp_uptime).state);
      - lambda: |-
          id(sleep_allowed) = !id(deep_sleep_override).state;  // Set based on local switch (off = allow)
          ESP_LOGI("sleep", "[BOOT] Deep sleep %s at boot (based on local override).",
                  id(sleep_allowed) ? "ALLOWED" : "PREVENTED");
      - lambda: |-
          std::string opt = id(logger_level_select).current_option();
          int level = ESPHOME_LOG_LEVEL_VERBOSE;  // Default
          if (opt == "NONE") level = ESPHOME_LOG_LEVEL_NONE;
          else if (opt == "ERROR") level = ESPHOME_LOG_LEVEL_ERROR;
          else if (opt == "WARN") level = ESPHOME_LOG_LEVEL_WARN;
          else if (opt == "INFO") level = ESPHOME_LOG_LEVEL_INFO;
          else if (opt == "DEBUG") level = ESPHOME_LOG_LEVEL_DEBUG;
          else if (opt == "VERBOSE") level = ESPHOME_LOG_LEVEL_VERBOSE;
          else if (opt == "VERY_VERBOSE") level = ESPHOME_LOG_LEVEL_VERY_VERBOSE;
          esphome::logger::global_logger->set_log_level(level);
          ESP_LOGI("boot", "Restored logger level: %s", opt.c_str());
      - if:
          condition:
            lambda: 'return !id(sleep_allowed);'
          then:
            - deep_sleep.prevent: deep_sleep_1
      
logger:
  level: VERY_VERBOSE  # Set to highest to enable all runtime select options; lower if you want to restrict
  baud_rate: 115200  # Keep for debugging; set to 0 once stable to disable serial logs

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  #use_address: 192.168.158.180
  ap:
    ssid: "XIAO Fallback"
    password: "12345678"

  # Fallback to AP if WiFi connection fails
  manual_ip:  # Optional for fixed IP after setup
    static_ip: 192.168.158.180
    gateway: 192.168.158.1
    subnet: 255.255.255.0

  on_disconnect:
    - lambda: |-
        ESP_LOGW("wifi", "WiFi disconnected - falling back to AP mode for reprovisioning.");  

api:
  encryption: 
    key: ${api_key}
 # password: ${api_key} # Plain API: Encryption disabled for testing.

ota:
  - platform: esphome
    password: ${ota_password}

captive_portal:

mdns:
  disabled: false

web_server:
  port: 80
  include_internal: true      

# Modular Packages
packages:
  max17048: !include packages/max17048-Seeed-Xiao-ESP32-C3.yaml #max17048 Fuel Guage
  pmsx003: !include packages/PMSX003-Seeed-Xiao-ESP32-C3.yaml #PMSX003, 7003
  board: !include packages/Board-Seeed-Xiao-ESP32-C3.yaml #Board specific GPIO, etc.
  base: !include packages/base.yaml  # Hardware, logger, wifi, api, ota, etc.
  sensors: !include packages/sensors.yaml  # All sensors and text_sensors
  sleep: !include packages/sleep.yaml  # Deep sleep, globals, intervals